# Picom - Estilo macOS
# Cantos arredondados + sombras suaves

# Backend
backend = "glx";

# Cantos arredondados
corner-radius = 24;

rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "class_g = 'xfce4-panel'",
  "class_g = 'Plank'"
];

# Sombras desativadas
shadow = false;

# Fading suave
fading = true;
fade-in-step = 0.04;
fade-out-step = 0.04;

# VSync
vsync = true;
